### PR TITLE
fix: check storage account type if parameter is missing

### LINKED ISSUE #1390: Volume provisioning fails with "InvalidHeaderValue" when using "smb" protocol and no skuName
**What happened**:

Using StorageClass with `protocol: smb` parameter and no `skuName` parameter fails to provision volumes with misleading message: `The value for one of the HTTP headers is not in the correct format`

Also tested with `Standard_LRS` storage account type and StorageClass with `skuName: Standard_LRS` - this works fine so I assume samba is supported with standard account and does not require premium.

**What you expected to happen**:

The driver should either detect storage account type via cloud provider or provide a more helpful message.

**How to reproduce it**:

1. Create premium storage account:
```
az storage account show --name premiumacct | jq '.sku'
{
  "name": "Premium_LRS",
  "tier": "Premium"
}
```

2. Create Samba premium StorageClass (without skuName parameter):
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2023-08-17T11:26:30Z"
  name: azurefile-premium
  resourceVersion: "51708"
  uid: 873edb60-b9cb-44c8-b32a-dff871f8079e
parameters:
  protocol: smb
  storageAccount: premiumacct
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

3. Attempt to create PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
    volume.kubernetes.io/storage-provisioner: file.csi.azure.com
  creationTimestamp: "2023-08-17T11:45:45Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: mypvc
  namespace: default
  resourceVersion: "57633"
  uid: d4ff26d0-0dac-4782-8abe-bb294090208c
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: azurefile-premium
  volumeMode: Filesystem
status:
  phase: Pending
```

4. Check PVC events for errors, type is not set (`type()`):
```
  Normal   Provisioning          15s (x5 over 31s)  file.csi.azure.com_rbednar-mycluster-01-qlr8j-master-2_8962c26e-4d7e-4425-b954-28f2bdcaee00  External provisioner is provisioning volume for claim "default/mypvc"
  Warning  ProvisioningFailed    15s                file.csi.azure.com_rbednar-mycluster-01-qlr8j-master-2_8962c26e-4d7e-4425-b954-28f2bdcaee00  failed to provision volume with StorageClass "azurefile-premium": rpc error: code = Internal desc = failed to create file share(pvc-d4ff26d0-0dac-4782-8abe-bb294090208c) on account(premiumacct) type() subsID() rg(rbednar-mycluster-01-qlr8j-rg) location() size(2), error: storage.FileSharesClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.\nRequestId:616414e9-801a-007d-3400-d1aad2000000\nTime:2023-08-17T11:46:01.6830388Z"
  Normal   ExternalProvisioning  6s (x3 over 31s)   persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator
```

5. Create StorageClass with `Premium_LRS`
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2023-08-17T11:55:01Z"
  name: azurefile-premium-sku
  resourceVersion: "60469"
  uid: 88d67eb5-54d9-4cbd-84ba-aa334892f23b
parameters:
  protocol: smb
  skuname: Premium_LRS
  storageAccount: premiumacct
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

6. Create PVC with this new StorageClass:
```
$ oc get pvc/mypvc -o json | jq '.spec.storageClassName , .metadata.name'
"azurefile-premium-sku"
"mypvc"
```

7. Verify PV created successfully
```
$ oc get pv/pvc-5f6331c1-2694-4ff4-baa9-a0755ad450c7 -o json | jq '.spec.claimRef.name'
"mypvc"
```

**Anything else we need to know?**:

1. Testing with `Premium_LRS` storage account while having StorageClass with `skuName: Standard_LRS` to create mismatch results in the same error:

` Warning  ProvisioningFailed    4s                file.csi.azure.com_rbednar-mycluster-01-qlr8j-master-2_8962c26e-4d7e-4425-b954-28f2bdcaee00  failed to provision volume with StorageClass "azurefile-mismatch": rpc error: code = Internal desc = failed to create file share(pvc-1669cbb0-7aae-4eee-9dee-55cf6cccbcae) on account(premiumacct) type(Standard_LRS) subsID() rg(rbednar-mycluster-01-qlr8j-rg) location() size(2), error: storage.FileSharesClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.\nRequestId:9e602865-301a-00b3-2e0c-d17b5c000000\nTime:2023-08-17T13:13:38.1743028Z"`

2. Documentation says the parameter [defaults](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/6ad4199f5754761f663e9ce3ca5d786ee610e1d0/docs/driver-parameters.md?plain=1#L25) to `Standard_LRS` but the driver does not seem apply this for samba, looking at the request while having no `skuName`/`storageAccountType` parameter in StorageClass the message is missing the type: `failed to create file share(xxx) on account(xxx) type()...`

**Environment**:

- CSI Driver version: v1.28.0
- Kubernetes version (use `kubectl version`):  v1.27.3+4aaeaec (OpenShift 4.14.0-ec.4)
- OS (e.g. from /etc/os-release): RHEL 8.6 (Ootpa)
- Kernel (e.g. `uname -a`): 5.14.0-284.23.1.el9_2.x86_64
- Install tools: openshift-install
- Others: N/A

### PR DESCRIPTION
**Pull request by RomanBednar**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

While using StorageClass with samba protocol without explicitly specifying strorage account type users get a misleading message and volume creation fails:

`Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.`

This happens in a scenario when creating a volume with size < 100Gi and storage account name (premium type) was provided as a parameter in `StorageClass` while `skuName` was omitted. Premium requirement is that a fileshare must have at least 100Gi in size.

Driver can lookup storage account type via storage account client and use that instead of relying on the`skuName` parameter that users otherwise need to set manually. 

**Which issue(s) this PR fixes**:

Fixes #1390

**Requirements**:
- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [X] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
`skuName` storage class parameter is now optional when using premium storage account with volume sizes below 100Gi
```

### CODE REVIEW

File: pkg/azurefile/controllerserver.go [hunk 1]
```diff
@@ -312,6 +312,16 @@ func (d *Driver) CreateVolume(ctx context.Context, req *csi.CreateVolumeRequest)
 		return nil, status.Errorf(codes.InvalidArgument, "fsType(%s) is not supported with protocol(%s)", fsType, protocol)
 	}
 
+	if account != "" && sku == "" {
```
Comment (andyzhangx) [inline pkg/azurefile/controllerserver.go:315]: also add `fileShareSize < minimumPremiumShareSize` check, that could save one `StorageAccountClient.GetProperties` call

Comment (RomanBednar) [reply pkg/azurefile/controllerserver.go]: Added, along with one more unit test to verify `StorageAccountClient.GetProperties` is not called in this case.

File: pkg/azurefile/controllerserver.go [hunk 2]
```diff
@@ -353,6 +353,17 @@ func (d *Driver) CreateVolume(ctx context.Context, req *csi.CreateVolumeRequest)
 	}
 
 	fileShareSize := int(requestGiB)
+
+	if account != "" && sku == "" && fileShareSize < minimumPremiumShareSize {
+		accountProperties, err := d.cloud.StorageAccountClient.GetProperties(ctx, subsID, resourceGroup, account)
+		if err != nil {
+			return nil, status.Errorf(codes.Internal, "failed to get properties on storage account account(%s) rg(%s), error: %v", account, resourceGroup, err)
```
Comment (andyzhangx) [inline pkg/azurefile/controllerserver.go:360]: pls set this a warning message since ` d.cloud.StorageAccountClient` may have no permission to get properties, and this is a nice to have fix.

Comment (RomanBednar) [reply pkg/azurefile/controllerserver.go]: Ok, changed.

**Comment by RomanBednar** [comment]
/hold

I get an error while obtaining storage account properties, need to investigate.

`E0824 12:33:51.882227       1 utils.go:81] GRPC error: rpc error: code = Internal desc = failed to get properties on storage account account(rbednarplrs) rg(), error: &{false 400 0001-01-01 00:00:00 +0000 UTC {"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2021-02-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}}`

**Comment by RomanBednar** [comment]
The only working combination I could find so far was when I set network [`APIVersion`](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/794f5fa89560cfb4b3a183bccdd73b8f3c4bd8f0/vendor/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/storageaccountclient/interface.go#L29) to `2023-07-01` and set `resourceGroup` parameter manually:

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-premium
parameters:
  protocol: smb
  storageAccount: premiumacct
  resourceGroup: rbednar-mycluster-01-4c6xn-rg
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

@andyzhangx Any idea how this should be handled? Seems like `GetProperties` call requires resource group name, but if that's the case this patch would not help much.

**Comment by RomanBednar** [comment]
I've found a similar [issue](https://github.com/Azure/azure-cli/issues/27239#issuecomment-1694903070) with CLI where the workaround was to add a resource group name, not sure if it might be related or if the same fix is planned for Azure SDK.

Anyway, `GetProperties` currently [requires](https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts/get-properties?tabs=HTTP#uri-parameters) the resource group name, so what we could do is to load the name from cloud config earlier and add a check (`resourceGroup != ""`) so we don't call `GetProperties` if it's not found.

Testing it with the same storage class I've posted in previous comment (but without `resourceGroup` paramenter) works fine for me.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/retest
