### PR TITLE
fix: Handle concurrent operation of NodeUnstage with NodeStage and NodeUnpublish with NodePublish

### LINKED ISSUE #253: Handle concurrent operation of NodeUnstage with NodeStage and NodeUnpublish with NodePublish
**What happened**:
we don't correctly handle concurrent processing of NodeUnstage call if a previous NodeStage was in-progress and same thing applies to NodeUnpublish call too.

The specs says, if an operation is in-progress for the volume then SP should return error code "10 ABORTED" - https://github.com/container-storage-interface/spec/blob/master/spec.md#timeouts

/kind bug

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by harshika-kashyap**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
we don't correctly handle concurrent processing of NodeUnstage call if a previous NodeStage was in-progress and same thing applies to NodeUnpublish call too.

The specs says, if an operation is in-progress for the volume then SP should return error code "10 ABORTED".

**Which issue(s) this PR fixes**:

Fixes #253

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:
```
none
```

**Release note**:
```
none
```

### CODE REVIEW

**Comment by harshika-kashyap** [comment]
CLA signed

File: pkg/azurefile/nodeserver.go [hunk 1]
```diff
@@ -38,6 +38,11 @@ import (
 	"golang.org/x/net/context"
 )
 
+var (
+	volumeStageInProgress   map[string]bool
```
Comment (andyzhangx) [inline pkg/azurefile/nodeserver.go:42]: map is not thread-safe, should use sync.Map

File: pkg/azurefile/nodeserver.go [hunk 2]
```diff
@@ -56,6 +61,10 @@ func (d *Driver) NodePublishVolume(ctx context.Context, req *csi.NodePublishVolu
 		return nil, status.Error(codes.InvalidArgument, "Staging target not provided")
 	}
 
+	volumeID := req.GetVolumeId()
+	volumePublishInProgress[volumeID] = true
+	defer delete(volumePublishInProgress, volumeID)
```
Comment (andyzhangx) [inline pkg/azurefile/nodeserver.go:66]: what about there are two `NodePublishVolume` calls in same time, shall we handle that?

**Review by andyzhangx — COMMENTED** [review]
it's better if we could add a unit test to test this scenario, thanks.

**Comment by harshika-kashyap** [comment]
CLA signed

File: pkg/azurefile/nodeserver.go (hunk 2 above)
Comment (andyzhangx) [reply pkg/azurefile/nodeserver.go:66]: could refer to https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/2014365ea7b3405e024be1d9552aa30d44da4a8b/pkg/gce-pd-csi-driver/node.go#L108-L110

Comment (harshika-kashyap) [reply pkg/azurefile/nodeserver.go:66]: sure.

**Comment by harshika-kashyap** [comment]
@andyzhangx done with the changes

**Comment by andyzhangx** [comment]
> @andyzhangx done with the changes

thanks, I would suggest use real lock, could refer to https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/2014365ea7b3405e024be1d9552aa30d44da4a8b/pkg/common/volume_lock.go#L44
though sync.Map is thread safe, while it cannot prevent race condition, use lock could solve the issue, thanks.

and it's better that `volumeLocks` could be in Driver struct fields, thanks.

File: pkg/azurefile/utils.go [hunk 3]
```diff
@@ -43,15 +43,17 @@ func newLockMap() *lockMap {
...
-	}
+	defer lm.Unlock()
 
-	lm.Unlock()
+	// check if entry exists, then it is not possible to acquire lock
+	if _, exists := lm.mutexMap[entry]; exists {
+		return false
+	}
+	lm.addEntry(entry)
 	lm.lockEntry(entry)
```
Comment (harshika-kashyap) [inline pkg/azurefile/utils.go:55]: @andyzhangx Should we use `sets.String` instead of `mutexMap map[string]*sync.Mutex`? It will simplify the logic. 

Similar to: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/2014365ea7b3405e024be1d9552aa30d44da4a8b/pkg/common/volume_lock.go#L32

Comment (harshika-kashyap) [reply pkg/azurefile/utils.go:55]: Please ignore. I'm still updating this.

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
could you also port this feature to blob & smb csi driver? thanks.
